### ISSUE TITLE
Trying to install using the latest gem, getting undefined method '+' error

### ISSUE THREAD

**Issue by tbeebe6** [santana/ruby-informix#3] opened 2017-04-26 12:47 UTC
root@ubuntuTest:~/.cpan/build# gem install ruby-informix
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-informix:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ruby-informix-0.8.2/ext
/usr/bin/ruby2.3 -r ./siteconf20170426-54696-pg5is0.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
        --with-informix-dir
        --without-informix-dir
        --with-informix-include
        --without-informix-include=${informix-dir}/include
        --with-informix-lib
        --without-informix-lib=${informix-dir}/lib
extconf.rb:25:in `block in <main>': undefined method `+' for nil:NilClass (NoMethodError)
        from extconf.rb:24:in `each'
        from extconf.rb:24:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ruby-informix-0.8.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-informix-0.8.2/gem_make.out

**Comment by santana** [comment] 2017-04-26 16:37
I see where the problem is. I will fix it tonight (CST)

**Comment by santana** [comment] 2017-04-26 21:57
It is fixed now @tbeebe6 @smosab Sorry for that :\

**Closed by santana** 2017-04-26 21:57 UTC
