### ISSUE TITLE
Error installing the gem on windows 7

### ISSUE THREAD

**Issue by ericksm3** [santana/ruby-informix#4] opened 2018-04-26 18:36 UTC
Hello, Santana!

Im having an error while trying to install the gem on a windows 7 64 bits instance with ruby 2.3.1

![error](https://user-images.githubusercontent.com/8135037/39324700-87441fb2-4966-11e8-939f-845bb87ec044.jpg)

It says that the directory or file coud not be found, but both exists. 

I went into the folder via command line and did the "esql -e informixc.ec" that the gem installation was trying to do, with the .ec file from here:

https://github.com/santana/ruby-informix/blob/master/ext/informixc.ec

And got not response:

![error2](https://user-images.githubusercontent.com/8135037/39324970-61ae24ea-4967-11e8-85ff-a5b1adb10945.jpg)

Can you please help me?

**Comment by ericksm3** [comment] 2018-05-09 19:42
For anyone looking for an answer, i had to use the odbc gem to connect with IBM informix and create a DSN for it. 

https://github.com/localytics/odbc_adapter

Closing the issue.

**Comment by santana** [comment] 2018-05-09 22:00
Hi @ericksm3 

it looks like the problem is that the path to the `esql` program includes spaces and I failed to add quotes around the variable holding that PATH.

Can you please try again, replacing this line:
```
%x{#{env} #{esql} -e informixc.ec}
```
with this:
```
%x{#{env} "#{esql}" -e informixc.ec}
```

**Comment by ericksm3** [comment] 2018-05-09 22:07
Hi, thanks for the answer.

Yeah it was that, i've tried changing folders but got another error, as described here: https://github.com/santana/ruby-informix/issues/2

Had to switch to ODBC still. Seems that its not working on windows 7.

**Comment by dcharan** [comment] 2018-05-17 23:44
I think its more to do with ruby version. I was on 1.9 and when I updated the ruby to  > 2.2 then I got the error #2

**Comment by santana** [comment] 2023-04-08 17:33
original and follow up issue were addressed; closing this issue.

**Closed as completed by santana** 2023-04-08 17:33 UTC
